Landing/urls.py
from django.urls import path
from Landing import views

app_name = 'Landing'

urlpatterns = [
    path('', views.land, name='landing'),
]

Main/urls.py
from django.urls import path
from Main import views

app_name = 'Main'


urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('signin/', views.signin, name='signin'),
]

Post/urls.py
from django.urls import path
from Post import views

app_name = 'Post'


urlpatterns = [
    path('', views.show, name='show'),
    path('form/', views.form, name='form'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

Qna/urls.py
from django.urls import path
from Qna import views


app_name = 'Qna'
urlpatterns = [
    path('', views.qna_post, name='qna_post'),
    path('form/', views.form, name='form'),
    path('<int:pk>/', views.qna_detail, name='qna_detail'),
    path('<int:pk>/edit/', views.qna_edit, name='qna_edit'),
    path('<int:pk>/delete/', views.delete, name='qna_delete'),
]

Translation/urls.py
from django.urls import path
from Translation import views
app_name = 'Translation'


urlpatterns = [
        path('', views.home, name='index'),
        path('signlanguage/', views.signlanguage, name='signlanguage'),
        path('braille/', views.braille, name='braille'),
        path('textlanguage/', views.textlanguage, name='textlanguage'),
        path('soundlanguage/', views.soundlanguage, name='soundlanguage'),
        path('textlanguage2/', views.textlanguage2, name='textlanguage2'),
        path('textlanguage2_trans/', views.textlanguage2_trans,
             name='textlanguage2_trans'),
]

User/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/<str:username>', views.delete, name='delete'),
    path('mypage/<str:username>', views.mypage, name='mypage'),
    path('find_id/', views.find_id, name='find_id'),
    path('find_id/show_id/', views.show_id, name='show_id'),
    path('find_pw/', views.find_pw, name='find_pw'),
    path('update/<str:username>', views.update, name='update'),

]

Landing/models.py
# from django.db import models

# Create your models here.

Main/models.py
# from django.db import models

# Create your models here.

Post/forms.py
from django import forms
from . models import Posting


class PostForm(forms.ModelForm):

    class Meta:
        model = Posting
        fields = ['title', 'visualhearing', 'pic', 'body']

    title = forms.CharField()
    pic = forms.ImageField()
    body = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control'})
        )
    visualhearing = forms.ChoiceField(choices=((0, '시각'), (1, '청각')))

Landing/views.py
from django.shortcuts import render


def land(request):
    return render(request, '../templates/landing.html')

Main/views.py
from django.shortcuts import render


def index(request):
    return render(request, '../templates/main.html')


def signup():
    return


def signin():
    return

Post/views.py
from django.shortcuts import get_object_or_404, redirect, render
from .models import Chatting, Posting
from User.models import User
from django.core.paginator import Paginator
from .forms import PostForm


def show(request):
    filter = request.GET.get('filter', '')
    search = request.GET.get('search', '')
    post_list = Posting.objects.all()
    if filter:
        if(filter == 'vision'):
            post_list = post_list.filter(visualhearing=0)
        elif(filter == 'hearing'):
            post_list = post_list.filter(visualhearing=1)
    if search:
        post_list = post_list.filter(title__contains=search)

    now_page = int(request.GET.get('page', 1))
    post_list = post_list.order_by('-post_idx')
    # 포스트 , 보여줄 게시글 개수
    p = Paginator(post_list, 10)
    info = p.get_page(now_page)

    # 페이지 마지막 번호
    last_page_num = 0
    for last_page in p.page_range:
        last_page_num = last_page

    context = {
        'info': info,
        'now_page': now_page,
        'last_page_num': last_page_num
    }
    return render(request, '../templates/post.html', context)


def form(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            posting = form.save(commit=False)
            user = User.objects.get(username=request.session['username'])
            posting.id = user
            posting.save()
            return redirect('/post/')
    else:
        form = PostForm()

    return render(
        request, '../templates/post_posting.html', {'form': form}
    )


def edit(request, pk):
    posting = Posting.objects.get(post_idx=pk)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=posting)
        if form.is_valid():
            posting.save()
            return redirect('/post/' + str(pk) + '/')
    else:
        form = PostForm(instance=posting)

    return render(
            request, '../templates/post_editing.html', {'form': form, 'pk': pk}
        )


def detail(request, pk):
    result = get_object_or_404(Posting, post_idx=pk)
    user = User.objects.get(username=result.id)
    if request.method == 'POST':
        comment = Chatting()
        comment.username = request.session['username']
        comment.chatting = request.POST['body']
        comment.post_idx = Posting.objects.get(post_idx=pk)
        comment.save()

    comments = Chatting.objects.filter(post_idx=pk)
    context = {
        'result': result,
        'user': user,
        'comments': comments,
        }
    return render(request, '../templates/post_detail.html', context)


def delete(request, pk):
    post = Posting.objects.get(post_idx=pk)
    post.delete()
    return redirect('/post/')

Qna/views.py
from django.shortcuts import get_object_or_404, redirect, render
from .forms import PostForm
from .models import Qna_Posting, Qna_Chatting
from User.models import User
from django.core.paginator import Paginator


def qna_post(request):
    qna_list = Qna_Posting.objects.all()
    now_page = int(request.GET.get('page', 1))
    qna_list = qna_list.order_by('-qna_idx')
    p = Paginator(qna_list, 10)
    info = p.get_page(now_page)

    last_page_num = 0
    for last_page in p.page_range:
        last_page_num = last_page

    context = {
        'info': info,
        'now_page': now_page,
        'last_page_num': last_page_num
    }
    return render(request, '../templates/qna.html', context)


def form(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            qna_posting = form.save(commit=False)
            user = User.objects.get(username=request.session['username'])
            qna_posting.id = user
            qna_posting.save()
            return redirect('/qna/')
    else:
        form = PostForm()

    return render(
        request, '../templates/qna_posting.html', {'form': form}
    )


def qna_edit(request, pk):
    qna_posting = Qna_Posting.objects.get(qna_idx=pk)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=qna_posting)
        if form.is_valid():
            qna_posting.save()
            return redirect('/qna/'+str(pk)+'/')
    else:
        form = PostForm(instance=qna_posting)

    return render(
            request, '../templates/qna_editing.html', {'form': form, 'pk': pk}
        )


def qna_detail(request, pk):
    result = get_object_or_404(Qna_Posting, qna_idx=pk)
    user = User.objects.get(username=result.id)

    if request.method == 'POST':
        comment = Qna_Chatting()
        comment.username = request.session['username']
        comment.chatting = request.POST['body']
        comment.qna_idx = Qna_Posting.objects.get(qna_idx=pk)
        comment.save()

    comments = Qna_Chatting.objects.filter(qna_idx=pk)
    context = {
        'result': result,
        'user': user,
        'comments': comments,
        }
    return render(request, '../templates/qna_detail.html', context)


def delete(request, pk):
    post = Qna_Posting.objects.get(qna_idx=pk)
    post.delete()
    return redirect('/qna/')

Translation/views.py
import os
import cv2
import time
import statistics
import mediapipe as mp
import numpy as np
from django.shortcuts import render
from django.http import StreamingHttpResponse, JsonResponse
from django.views.decorators import gzip
from PIL import ImageFont, ImageDraw, Image
from google.protobuf.json_format import MessageToDict
from gtts import gTTS
from keras.models import load_model
from Translation import model_wts
from Hanguel import decompose

script_dir = os.path.dirname(__file__)
translated_sentence = []
action_seq = []
translated_sentence2 = []


def home(request):
    context = {'data': translated_sentence}

    return render(request, '../templates/translation.html', context)


def textlanguage(request):
    global translated_sentence
    language = request.GET.get('language')
    text = translated_sentence
    if language == 'braille':
        text = text.replace(' ', '')
        return braille(text)
    elif language == 'soundlanguage':
        return soundlanguage(text)
    elif language == 'text':
        return JsonResponse({'text': text})


def soundlanguage(text):
    tts = gTTS(text=text, lang='ko')
    filename = time.strftime("%Y%m%d-%H%M%S")
    tts.save(os.path.join('../', script_dir,
                          f"../static/audio/{filename}.mp3"))
    context = {'audio_path': filename}
    return JsonResponse(context)


def braille(text):
    arr = decompose.Decompose(text)
    dict = {0: 'chosung', 1: 'joongsung', 2: 'jongsung'}
    display = []
    for word in arr:
        for idx, syllable in enumerate(word):
            if (syllable == '') or (idx == 0 and syllable == 'ㅇ'):
                continue
            elif syllable in '0123456789.':
                display.append(f'nums/{syllable}')
            else:
                display.append(f'{dict[idx%3]}/{syllable}')
    height_num = len(display) // 10
    result_width, result_height = 10 * 164, 231 * height_num
    result = Image.new("RGBA", (result_width, result_height))
    for idx, b in enumerate(display):
        path = f'../static/bralille_set/{b}.png'
        input = Image.open(os.path.join('../', script_dir, path))
        result.paste(im=input, box=(((idx) % 10) * 164, (idx // 10) * 231))
    result = result.resize((int(result.width / 7), int(result.height / 7)))
    filename = time.strftime("%Y%m%d-%H%M%S")
    save_path = f"../static/bralille_translated/{filename}.png"
    result.save(os.path.join('../', script_dir, save_path))
    context = {'img_path': filename}
    return JsonResponse(context)


def textlanguage2(request):
    global translated_sentence2
    translated_sentence2 = request.GET.get('text')
    return JsonResponse({})


def textlanguage2_trans(request):
    global translated_sentence2
    language = request.GET.get('language')
    text = translated_sentence2
    if language == 'braille':
        text = text.replace(' ', '')
        return braille(text)
    elif language == 'soundlanguage':
        return soundlanguage(text)
    elif language == 'signlanguage':
        context = {'img_path': text}
        return JsonResponse(context)


# 웹 스트리밍 부분 --
class VideoCamera(object):

    def __init__(self):
        self.video = cv2.VideoCapture(0, cv2.CAP_DSHOW)

    # 카메라 정지
    def __del__(self):
        self.video.release()
        return

    # 영상을 jpg 바이너리로 변환하여 리턴
    def get_frame(self, model, actions, seq_length, mp_hands, mp_drawing, hands, seq):
        global translated_sentence
        global action_seq

        ret, image = self.video.read()
        if ret:

            image = cv2.flip(image, 1)
            result = hands.process(image)

            if result.multi_hand_landmarks is not None:
                hand_arr = []
                right_hand, left_hand = np.zeros((21, 3)), np.zeros((21, 3))
                for res in result.multi_hand_landmarks:
                    joint = np.zeros((21, 3))
                    for j, lm in enumerate(res.landmark):
                        joint[j] = [lm.x, lm.y, lm.z]

                    v1 = joint[[0, 1, 2, 3, 0, 5, 6, 7, 0, 9, 10,
                                11, 0, 13, 14, 15, 0, 17, 18, 19], :3]
                    v2 = joint[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
                                12, 13, 14, 15, 16, 17, 18, 19, 20], :3]
                    v = v2 - v1
                    v = v / np.linalg.norm(v, axis=1)[:, np.newaxis]
                    angle = np.arccos(np.einsum(
                        'nt,nt->n',
                        v[[0, 1, 2, 4, 5, 6, 8, 9, 10,
                           12, 13, 14, 16, 17, 18], :],
                        v[[1, 2, 3, 5, 6, 7, 9, 10, 11,
                           13, 14, 15, 17, 18, 19], :]
                        ))
                    angle = np.degrees(angle)  # Convert radian to degree
                    angle_label = np.array(angle, dtype=np.float32)
                    handedness_dict = MessageToDict(result.multi_handedness[0])
                    if handedness_dict['classification'][0]['label'] == 'Right':
                        right_hand = joint
                    else:
                        left_hand = joint

                    hand_arr.extend(angle_label)
                    mp_drawing.draw_landmarks(
                        image, res, mp_hands.HAND_CONNECTIONS
                        )

                if len(hand_arr) == 15:
                    handedness_dict = MessageToDict(result.multi_handedness[0])
                    if handedness_dict['classification'][0]['label'] == 'Right':
                        hand_arr = np.concatenate((np.zeros(15), hand_arr))
                    else:
                        hand_arr = np.concatenate((hand_arr, np.zeros(15)))
                elif len(hand_arr) > 30:
                    return None

                hand_distance = left_hand - right_hand
                hand_distance /= \
                    np.linalg.norm(hand_distance, axis=1)[:, np.newaxis]
                hand_arr = np.concatenate((hand_arr, hand_distance.flatten()))
                seq.append(hand_arr)

                if len(seq) < seq_length:
                    return None

                input_data = np.expand_dims(np.array(
                    seq[-seq_length:], dtype=np.float32
                    ), axis=0)
                y_pred = model.predict(input_data).squeeze()
                i_pred = int(np.argmax(y_pred))
                conf = y_pred[i_pred]
                if conf < 0.8:
                    return None

                action = actions[i_pred]
                action_seq.append(action)

                if len(action_seq) < 3:
                    return None
                this_action = '?'
                if action_seq[-1] == action_seq[-2] == action_seq[-3]:
                    this_action = action

                font = ImageFont.truetype("fonts/gulim.ttc", 40)
                image_pil = Image.fromarray(image)
                draw = ImageDraw.Draw(image_pil)
                draw.text((30, 50), this_action, font=font, fill=(1, 1, 1))
                image = np.array(image_pil)

            else:
                if len(action_seq) > 0:
                    print(translated_sentence)
                    translated_sentence.append(statistics.mode(action_seq))
                    action_seq = []

            ret, jpeg = cv2.imencode('.jpg', image)
            return jpeg.tobytes()
        return None


def gen(camera):
    model = load_model("Translation/file/mp_model.h5")
    actions = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10',
               '가렵다', '개', '공원', '금요일', '내년', '내일', '냄새나다',
               '누나', '동생', '수화', '물', '아래', '바다', '배고프다',
               '병원', '불', '산', '삼키다', '선생님', '수요일', '아빠',
               '아파트', '앞', '어제', '어지러움', '언니', '엄마', '오늘',
               '오른쪽', '오빠', '올해', '왼쪽', '월요일', '위에', '음식물',
               '일요일', '자동차', '작년', '집', '친구', '택시', '토요일',
               '학교', '형', '화요일', '화장실', '가다', '감사합니다',
               '괜찮습니다', '나', '남자', '내리다', '당신', '돕다', '맞다',
               '모르다', '미안합니다', '반드시', '부탁합니다', '빨리', '수고',
               '수화', '슬프다', '싫다', '아니다', '안녕하세요', '알다', '없다',
               '여자', '오다', '있다', '잘', '좋다', '주다', '타다', '끝',
               '무엇', '키우다', '우리', '단체', '번역', '만들다', '사랑합니다', '어디']

    os.environ['CUDA_VISIBLE_DEVICES'] = '1'
    os.environ['TF_FORCE_GPU_ALLOW_GROWTH'] = 'true'
    seq_length = 20

    mp_hands = mp.solutions.hands
    mp_drawing = mp.solutions.drawing_utils
    hands = mp_hands.Hands(max_num_hands=2,
                           min_detection_confidence=0.5,
                           min_tracking_confidence=0.5)

    seq = []

    while True:
        frame = camera.get_frame(model, actions, seq_length,
                                 mp_hands, mp_drawing, hands, seq)
        if frame:
            yield(b'--frame\r\n'
                  b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')


@gzip.gzip_page
def signlanguage(request):
    global translated_sentence
    try:
        status = request.GET.get('status')
        cam = VideoCamera()
        if status == 'false':
            cam.__del__()
            sentence = model_wts.predict_mo(translated_sentence)
            translated_sentence = sentence
            return JsonResponse({'data': sentence})
        return StreamingHttpResponse(gen(cam),
                                     content_type="multipart/x-mixed-replace;\
                                                    boundary=frame")
    except Exception:
        print("error")
        pass

templates/base.html
<!DOCTYPE HTML>
{% load static %}
<!--
	Telephasic by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>너나들이</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
		<link rel="stylesheet" href="{% static 'css/flexslider.css' %}" type="text/css">
		<link href="{% static 'css/styles.css' %}" rel="stylesheet">
		<link href="{% static 'css/queries.css' %}" rel="stylesheet">
		<link href="{% static 'css/jquery.fancybox.css' %}" rel="stylesheet">
		<link rel="stylesheet" href="{% static 'css/main.css' %}"/>
	</head>
	<body >
			<div>
				<div id="header" class="container">
					<!-- Logo -->
						<h1 id="logo"><a href="{% url 'Main:index' %}">너나들이</a></h1>

					<!-- Nav -->
						<nav id="nav" style='background-image: url("/static/img/hero.jpg");'>
							<ul style="margin-left: 10em;">
								<li><a href="{% url 'Post:show' %}">게시판</a>
									<ul>
										<li><a href="{% url 'Post:show' %}">커뮤니티</a></li>
										<li><a href="{% url 'Qna:qna_post' %}">Q&A</a></li>
									</ul>
								</li>
								<li style="margin-left: 25em;"> <a href="{% url 'Translation:index' %}">번역</a></li>

							</ul>
							<ul style="float: right;">
								{% if request.session.username%}
								<li style="margin-right:5em">
									<a href="#">{{ request.session.username }}님</a>
									<ul>
										<li><a href="{% url 'user:mypage' user.username %}">회원정보</a></li>
										<li><a href="{% url 'user:logout' %}">로그아웃</a></li>
									</ul>
								</li>
								{% else %}
								<li>
									<a href="{% url 'user:login' %}">로그인</a>
									<a href="{% url 'user:signup' %}">회원가입</a>
								{% endif %}
								</li>
							</ul>
						</nav>
				</div>	
			</div>
            {% block content %}
            {% endblock %}
			<script src="{% static 'js/jquery.min.js' %}"></script>
			<script src="{% static 'js/jquery.dropotron.min.js' %}"></script>
			<script src="{% static 'js/browser.min.js' %}"></script>
			<script src="{% static 'js/breakpoints.min.js' %}"></script>
			<script src="{% static 'js/util.js' %}"></script>
			<script src="{% static 'js/main.js' %}"></script>
	</body>

</html>

templates/post_detail.html
{% extends 'base.html' %}

<style>
  .center-block{display:block;margin-right:auto;margin-left:auto}
  .link-secondary{color:#6c757d}.link-secondary:focus,.link-secondary:hover{color:#565e64}
  /* .justify-content-md-end{justify-content:flex-end!important}
  .d-grid{display:grid!important}
  .gap-2{gap:.5rem!important}
  .d-md-flex{display:flex!important} */
</style>

{% block content %}
<body style="justify-content : center; text-align: center;">
  <section class="section-margin--small mb-5">
    <div class="container">
      <div class="row">
                {% comment %} 게시판 시작 {% endcomment %}
        <div class="d-grid gap-2 d-md-flex justify-content-md-end" style="margin-top:60px;"></div>
          <table class="table">
            <tr>
							<th scope="col" class="text-left" style="padding-top:40px;"><h3>제목 : <strong>{{result.title}}</strong></h3> <br> 
                {% ifequal request.session.username  user.username %}
                <a href="{%url 'Post:edit' result.post_idx %}" class="link-secondary" style="margin-left: 55em;">수정</a>
                <a href="{%url 'Post:delete' result.post_idx %}" class="link-secondary" style="margin-left: 1em;">삭제</a>
                <a href="{% url 'Post:show' %}" class="link-secondary" style="margin-left: 1em;">목록</a>     
        
                {% else %}     
                <a href="{% url 'Post:show' %}" class="link-secondary" style="margin-left: 61em;">목록</a>    
                {% endifequal %} 
              </th>
            </tr>
            </tr>
            <tr>
              <td> 
                {% if result.pic %}
                <center><img src="/media/{{ result.pic }}" class="img-responsive left-block"style="width:400px; height:400px;"></center>
                {% endif %}
              </td>
            </tr>
            <tr>
              <td style="text-align: left;"><span> {{result.body}} </span></td>
            </tr>
          </table>
        <div style="display:flex">
                {% comment %} 해당 게시판을 작성한 사용자만 수정/삭제 버튼 활성화 {% endcomment %}


        </div>
      </div>
      <h1 style="text-align: left;">comment</h1>
        {% comment %} 로그인한 회원만 댓글 작성 가능 {% endcomment %}
        {% if request.session.username %}
        <form method="POST">
        {% csrf_token %}
          <textarea class="form-control" rows="3" name="body"></textarea>
          <br>
          <button type="submit" class="btn btn-default btn-lg float-right">등록</button>
        </form>
        {% endif %}

            {% comment %} 댓글 게시판 {% endcomment %}
        <table class='table'>
          {% for comment in comments %}
            <tr>
              <td>
                <div class="container" style="display: flex;justify-content: space-between;text-align: start;">
                  <p><span class="glyphicon glyphicon-user"> </span>{{comment.username}}</p>
                  <p> {{comment.chatting}} </p>
                  <p class="text-secondary"> <small> {{comment.date}} </small> </p>
                </div>
              </td>
            </tr>
          {% endfor %}
        </table>
      </div>
    </section>
</body>
<!-- ================ category section end ================= -->
{% endblock%}

templates/post_posting.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE HTML>

<!--
	Telephasic by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
	{% block content %}
<!-- ================ category section start ================= -->
<body style="justify-content : center; text-align: center;">
	<div class="container" style="margin-top: 2em;">
		<div class="row">
			<div class="mx-auto col-xl-9">
				<form action="{% url 'Post:form' %}" method="post" enctype="multipart/form-data">
					{% csrf_token %}
					<table class="mx-auto table">
						<tr>
							<td>
								<h4>Title</h4>
							</td>
							<td>{{form.title}}</td>
						</tr>
						<tr>
							<td>
								<h4>시각/청각</h4>
							</td>
							<td>{{form.visualhearing}}</td>
						</tr>
						<tr>
							<td>
								<h4>Picture</h4>
							</td>
							<td> {{form.pic}} </td>
						</tr>
						<tr>
							<td>
								<h4>Body</h4>
							</td>
							<td>{{form.body}}</td>
						</tr>
					</table>
					{% if form.errors %} 
					<span style="color: red">{{ form.errors }} </span> 
					{% endif %} 
					
					<div class="col text-center">
						<button type="submit" class="btn btn-outline-secondary mx-auto">등록</button>
						<button class="btn btn-outline-secondary">
							<a href="{% url 'Post:show' %}">취소</a>
						</button>
					</div>
				</form>
			</div>
		</div>
		</div>
	</body>
		{% endblock %}
</html>

templates/qna_detail.html
{% extends 'base.html' %}
{% load static %}

<style>
  .center-block{display:block;margin-right:auto;margin-left:auto}
  .link-secondary{color:#6c757d}.link-secondary:focus,.link-secondary:hover{color:#565e64}
  /* .justify-content-md-end{justify-content:flex-end!important}
  .d-grid{display:grid!important}
  .gap-2{gap:.5rem!important}
  .d-md-flex{display:flex!important} */
</style>

<html>
	{% block content %}
	<body style="justify-content : center; text-align: center;">
    <section class="section-margin--small mb-5">
      <div class="container">
            <div class="row" style="justify-content:center;">

                {% comment %} 게시판 시작 {% endcomment %}
                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                  
                </div>
                <table class="table">
                  <tr>
								    <th scope="col" class="text-left">{{result.title}}</th>
                  </tr>
                  <tr>
                    <td> 
                      {% if result.pic %}
                      <img src="/media/{{ result.pic }}" class="img-responsive left-block"
                        style="width:200px; height:200px;"> 
                      {% endif %}
                    </td>
                  </tr>
                  <tr>
                    <td style="text-align: left;"><span> {{result.body}} </span></td>
                  </tr>
                </table>
              <div style="display:flex">
                {% comment %} 해당 게시판을 작성한 사용자만 수정/삭제 버튼 활성화 {% endcomment %}

                {% ifequal request.session.username user.username %}
                <a href="{%url 'Qna:qna_edit' result.qna_idx %}" class="link-secondary" style="margin-right: 5em;">수정</a>
                <a href="{%url 'Qna:qna_delete' result.qna_idx %}" class="link-secondary" style="margin-right: 5em;">삭제</a>
                {% endifequal %}
                <a href="{% url 'Qna:qna_post' %}" class="link-secondary" style="margin-right: 10em;">목록</a>
                
              </div>
            </div>

            <h1 style="text-align: left;">comment</h1>

            {% comment %} 로그인한 회원만 댓글 작성 가능 {% endcomment %}
            {% if request.session.username %}
            <form method="POST">
              {% csrf_token %}
              <textarea class="form-control" rows="3" name="body"></textarea>
              <button type="submit" class="btn btn-default btn-lg float-right">등록</button>
            </form>
            {% endif %}

            {% comment %} 댓글 게시판 {% endcomment %}
            <table class='table'>
              {% for comment in comments %}
              <tr>
                <td>
                  <div class="container" style="display: flex;justify-content: space-between;text-align: start;">
                    <p><span class="glyphicon glyphicon-user"> </span>{{comment.username}}</p>
                    <p> {{comment.chatting}} </p>
                    <p class="text-secondary"> <small> {{comment.date}} </small> </p>
                  </div>
                </td>
              </tr>
              {% endfor %}
            </table>
          </div>
    </section>
  </body>
</html>
<!-- ================ category section end ================= -->
{% endblock%}