Post/urls.py
from django.urls import path
from Post import views

app_name = 'Post'


urlpatterns = [
    path('', views.show, name='show'),
    path('form/', views.form, name='form'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

Qna/urls.py
from django.urls import path
from Qna import views


app_name = 'Qna'
urlpatterns = [
    path('', views.qna_post, name='qna_post'),
    path('form/', views.form, name='form'),
    path('<int:pk>/', views.qna_detail, name='qna_detail'),
    path('<int:pk>/edit/', views.qna_edit, name='qna_edit'),
    path('<int:pk>/delete/', views.delete, name='qna_delete'),
]

Team_02/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('User.urls')),
    path('', include('Landing.urls'), name='land'),
    path('main/', include('Main.urls'), name='main'),
    path('post/', include('Post.urls'), name='post'),
    path('qna/', include('Qna.urls'), name='qna'),
    path('translation/', include('Translation.urls'), name='translation'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

User/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/<str:username>', views.delete, name='delete'),
    path('mypage/<str:username>', views.mypage, name='mypage'),
    path('find_id/', views.find_id, name='find_id'),
    path('find_id/show_id/', views.show_id, name='show_id'),
    path('find_pw/', views.find_pw, name='find_pw'),
    path('update/<str:username>', views.update, name='update'),

]

User/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser
from datetime import datetime


class UserManager(BaseUserManager):
    def create_user(self, username, name, email, password=None):
        if not username:
            raise ValueError("아이디를 입력해주세요.")
        if not name:
            raise ValueError("이름을 입력해주세요.")
        if not email:
            raise ValueError("이메일을 입력해주세요.")

        user = self.model(
            username=username,
            name=name,
            email=self.normalize_email(email),
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, name, email, password):
        user = self.create_user(
            username=username,
            name=name,
            email=self.normalize_email(email),
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):

    username = models.CharField(unique=True, max_length=150, blank=True)
    name = models.CharField(max_length=128)
    email = models.EmailField(max_length=128, unique=True)
    date_joined = models.DateField(default=datetime.now)
    is_staff = models.IntegerField(blank=True, null=True)
    is_active = models.IntegerField(blank=True, null=True)
    is_admin = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'username'   # 식별자로 사용할 필드.
    REQUIRED_FIELDS = ['name', 'email']            # 회원가입 때 필수 입력필드.

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

User/forms.py
from django import forms
from .models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import authenticate


class SignupForm(UserCreationForm):
    username = forms.CharField(max_length=150,
                               label="아이디",
                               error_messages={'unique': "이미 존재하는 아이디입니다."})
    name = forms.CharField(max_length=128,
                           label="이름")
    email = forms.EmailField(max_length=128,
                             label="이메일",
                             error_messages={'unique': "이미 존재하는 이메일입니다."})

    class Meta:
        model = User
        fields = ("username", 'name', 'email', "password1", "password2")


class LoginForm(forms.ModelForm):
    password = forms.CharField(label='비밀번호', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'password')
        labels = {
            "username": "아이디",
        }

    def clean(self):
        if self.is_valid():
            username = self.cleaned_data['username']
            password = self.cleaned_data['password']
            if not authenticate(username=username, password=password):
                raise forms.ValidationError("로그인 실패")


class UpdateForm(UserChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].disabled = True
        self.fields['name'].disabled = True

    class Meta:
        model = User
        fields = ("username", 'name', 'email', )
        labels = {
            "username": "아이디",
            "name": "이름",
            "email": "이메일",
        }


class PasswordVerificationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].disabled = True

    class Meta:
        model = User
        fields = ('username', 'password')
        labels = {
            "username": "아이디",
            "password": "비밀번호"
        }

    def clean(self):
        if self.is_valid():
            username = self.cleaned_data['username']
            password = self.cleaned_data['password']
            if not authenticate(username=username, password=password):
                raise forms.ValidationError("비밀번호가 일치하지 않습니다.")


class ParamForm(forms.Form):
    username = forms.CharField(label='아이디')
    email = forms.CharField(label='이메일')

User/views.py
import random
from django.shortcuts import render, redirect
from django.http import JsonResponse
from .models import User
from Post.models import Posting
from .forms import SignupForm, LoginForm, UpdateForm, \
                   PasswordVerificationForm, ParamForm
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import authenticate, update_session_auth_hash
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.hashers import make_password
from django.core.mail import EmailMessage
from django.core.exceptions import ObjectDoesNotExist
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode


def signup(request):
    context = {}
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/user/login')
        else:
            context['signup_form'] = form
    else:
        form = SignupForm()
        context['signup_form'] = form
    return render(request, '../templates/User/signup.html', context)


def login(request):
    context = {}
    user = request.user
    if user.is_authenticated:
        return redirect("/main")
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(username=username, password=password)
            if user:
                auth_login(request, user)
                request.session['username'] = username
                return redirect("/main")
    else:
        form = LoginForm()
    context['login_form'] = form
    return render(request, "../templates/User/login.html", context)


def logout(request):
    auth_logout(request)
    return redirect('/main')


def delete(request, username):
    context = {}
    if request.method == 'POST':
        form = PasswordVerificationForm(request.POST, instance=request.user)
        if form.is_valid():
            password = request.POST.get('password')
            user = authenticate(username=username, password=password)
            if user:
                user.delete()
                logout(request)
                return redirect('/main')
            else:
                context['error'] = '회원정보가 일치하지 않습니다.'
                render(request, "../templates/User/delete.html", context)
    else:
        form = PasswordVerificationForm(instance=request.user)
    context['password_form'] = form
    return render(request, "../templates/User/delete.html", context)


def update(request, username):
    context = {}
    if request.method == 'POST':
        form = UpdateForm(request.POST, instance=request.user)
        form2 = PasswordChangeForm(request.user, request.POST)
        if form.is_valid() and form2.is_valid():
            form.save()
            user2 = form2.save()
            update_session_auth_hash(request, user2)
            logout(request)
            return redirect('/user/login')
    else:
        form = UpdateForm(instance=request.user)
        form2 = PasswordChangeForm(request.user)
    context['update_form'] = form
    context['pwupdate_form'] = form2
    return render(request, '../templates/User/update.html', context)


def find_id(request):
    return render(request, '../templates/User/find_id.html')


def show_id(request):
    confirm_email = request.GET.get('confirm_email')
    confirm_id = User.objects.get(email=confirm_email).username
    context = {'confirm_id': confirm_id}
    return JsonResponse(context)


def mypage(request, username):
    user = User.objects.get(username=username)
    context = {}
    posts = Posting.objects.filter(id=user.id).values().order_by('-date')
    if len(posts) >= 5:
        posts = posts[0:5]
    context['posts'] = posts
    if user:
        context['username'] = user
        return render(request, '../templates/User/mypage.html', context)
    else:
        return redirect('/main')


def active_message(username_64):
    LENGTH = 8
    string_pool = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ' +\
        'abcdefghijklmnopqrstuvwxyz' +\
        '0123456789!@#$%^&*'
    newpassword = ""

    for _ in range(LENGTH):
        newpassword += random.choice(string_pool)

    user = User.objects.get(username=force_text
                            (urlsafe_base64_decode(username_64))
                            )
    user.password = make_password(newpassword)
    user.save()
    return f"비밀번호 재발급\n\n 비밀번호 : {newpassword}\n\n감사합니다."


def find_pw(request):
    context = {}
    if request.method == 'POST':
        form = ParamForm(request.POST)
        try:
            username = request.POST.get('username')
            email = request.POST.get('email')
            confirm_username = User.objects.get(email=email).username
            confirm_email = User.objects.get(username=username).email
            if confirm_email == email and confirm_username == username:
                user = User.objects.get(username=username)
                username_64 = urlsafe_base64_encode(force_bytes(username))
                message_data = active_message(username_64)
                mail_title = "비밀번호 재발급"
                mail_to = user.email
                email = EmailMessage(mail_title, message_data, to=[mail_to])
                email.send()
                return redirect('/user/login')
            context['error'] = '일치하는 정보가 없습니다.'
        except ObjectDoesNotExist:
            context['error'] = '일치하는 정보가 없습니다.'
    else:
        form = ParamForm()
    context['param_form'] = form
    return render(request, "../templates/User/find_pw.html", context)

templates/User/delete.html
{% extends 'base.html' %}

{% block content %}

<div style="padding:5%;display: flex;flex-direction: column;align-items: center;">

<h2>회원 탈퇴</h2>
<form method='post' style="width:33%;height:30%">{% csrf_token %}
    {% for field in password_form %}
        <p>
            {{field.label_tag}}

            {{field}}

            {% if field.help_text %}
                <small style="color:grey;">{{field.help_text}}</small>
            {% endif %}

            {% for error in field.errors %}
                <small style="color:red;">{{error}}</small>
            {% endfor %}

            {% if password_form.non_field.errors%}
                <div style="color:red">
                    <p>{{password_form.non_field.errors}}</p>
                </div>
            {% endif %}

        </p>
    {% endfor %}
    <div style="display: flex;flex-direction: column;align-items: center;">
    <p><strong style="color:red;">{{ error }}</strong></p>
    <button type="submit">회원탈퇴</button>
    </div>
</div>
{% endblock %}

templates/User/find_id.html
{% extends 'base.html' %}

{% block content %}

<div style="padding:5%;display: flex;flex-direction: column;align-items: center;">

<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

<script>
    function show_id(){
        var confirm_email = document.getElementById('getemail_id').value
        
        $.ajax({
            url: "{% url 'user:show_id' %}",
            type: "GET",
            dataType: "json",
            data: {'confirm_email': confirm_email},
            success: function(data){
                document.all('div_id').innerHTML="아이디는 " + data['confirm_id'] + " 입니다.";
            }, error: function(e) { 
                document.all('div_id').innerHTML="<p><strong style='color:red'>찾으시는 아이디가 없습니다.</strong></p>";
            } 
            
        });
    }
    </script>
<p>이메일을 입력해주세요.</p>
<form method="POST" action="{% url 'user:find_id' %}" style="width:33%;height:30%; margin-bottom: 1.5em;">
    {% csrf_token %}
    <input id="getemail_id" type="text" name="confirm_email">
    <button class="send_btn" onclick="show_id()" type="button" style="display: block;margin: 0 auto; margin-top: 1.5em">아이디 찾기</button>
</form>
<div id="div_id" style="display: block;margin: 0 auto; margin-top: 1.5em"></div>

<div>
{% endblock %}

templates/User/find_pw.html
{% extends 'base.html' %}

{% block content %}

<div style="padding:5%;display: flex;flex-direction: column;align-items: center;">
<p>입력하신 이메일로 새로운 비밀번호를 전송합니다.</p>
<form method='post' action="{% url 'user:find_pw' %}" style="width:33%;height:30%">{% csrf_token %}
    {% for field in param_form %}
        <p>
            {{field.label_tag}}

            {{field}}

        </p>
    {% endfor %}
    <button type="submit" style="display: block;margin: 0 auto; margin-top: 1.5em; margin-bottom: 1.5em">비밀번호 재발급</button>
</form>


<p ><strong style="color:red">{{ error }}</strong></p>

</div>

{% endblock %}

templates/User/login.html
{% extends 'base.html' %}

{% block content %}

<div style="padding:5%;display: flex;flex-direction: column;align-items: center;">
    <h2>로그인</h2>
    <br><br>
    <form method='post' style="width:33%;height:30%">{% csrf_token %}
        {% for field in login_form %}
            <p>
                {{field.label_tag}}
    
                {{field}}
    
                {% if field.help_text %}
                    <small style="color:grey;">{{field.help_text}}</small>
                {% endif %}
    
                {% for error in field.errors %}
                    <small style="color:red;">{{error}}</small>
                {% endfor %}
    
                {% if login_form.non_field.errors%}
                    <div style="color:red">
                        <p>{{login_form.non_field.errors}}</p>
                    </div>
                {% endif %}
    
            </p>
        {% endfor %}
        <button type="submit" style="display: block;margin: 0 auto;">로그인</button>
        <div style="display: block;margin: 0 auto;display: flex;flex-direction: row;justify-content: center;margin-top:1.5em">
        <a href="{% url 'user:find_id'%}" style="margin-right:0.75em">ID 찾기</a>
        <a href="{% url 'user:find_pw'%}" style="margin-left:0.75em">PW 찾기</a>
        </div>
    </form>
</div>

{% endblock %}

templates/User/mypage.html
{% extends 'base.html' %}

<style>
    .btn_btn-success{
        background-color:white;
        border: solid 1px #c2c7cc;
        border-radius: 0.35em;
        padding: 0.8em 2em 0.8em 2em;
        cursor: pointer;
    }
 
</style>

{% block content %}
    <div style="padding:5%;display: flex;flex-direction: column;align-items: center;">
    <div style="width:100%">
        <div class="left" style="width: 50%;float: left; box-sizing: content-box;margin:auto;display: flex;flex-direction: column;align-items: center;">
            <strong><h2>MY PAGE</h2></strong><br>
            <h3>ID : {{ user.username }}</h3><br>
            <h3>Name : {{ user.name }}</h3><br>
            <h3>Email : {{ user.email }}</h3><br>
            <div>
                <div class="left" style="width: 50%;float: left; box-sizing: border-box;margin:auto;display: flex;flex-direction: column;align-items: center;">
                    <a href="{% url 'user:update' user.username %}">
                        <button class="btn_btn-success" style="margin-right:0.75em">
                        <strong>정보 수정</strong></button>
                    </a>
                </div>
                <div class="right" style="width: 50%;float: left; box-sizing: border-box;margin:auto;display: flex;flex-direction: column;align-items: center;">
                    <a href="{% url 'user:delete' user.username %}">
                        <button class="btn_btn-success" style="margin-left:0.75em">
                        <strong>회원 탈퇴</strong></button>
                    </a>
                </div>
            </div>
        </div>
        <div class="right" style="width: 50%;float: left; box-sizing: content-box;margin:auto;display: flex;flex-direction: column;align-items: center;">
            <strong><h2>최근 작성글</h2></strong><br>
            {% for post in posts %}
                <strong style="font-size:15px;color:white;">
                    <h3><a href="{% url 'Post:detail' post.post_idx %}" style="color:black">
                        {{ post.title }}
                    </a></h3>
                </strong><br>
            {% endfor %}
        </div>
    </div>
    </div>
{% endblock %}

templates/User/signup.html
{% extends 'base.html' %}

{% block content %}
<div style="padding:5%;display: flex;flex-direction: column;align-items: center;">
<h2> Sign Up </h2>
<br><br>
<form method='post'>{% csrf_token %}
    {% for field in signup_form %}
        <p>
            {{field.label_tag}}

            {{field}}

            {% if field.help_text %}
                <small style="color:grey;">{{field.help_text}}</small><br>
            {% endif %}

            {% for error in field.errors %}
                <small style="color:red;">{{error}}</small>
            {% endfor %}
        </p>
    {% endfor %}
    <button type="submit" style="display: block;margin: 0 auto;">회원가입</button>
</form>
</div>
{% endblock %}

templates/User/update.html
{% extends 'base.html' %}

{% block content %}

<div style="padding:5%;display: flex;flex-direction: column;align-items: center;">

<h2>회원 정보 수정</h2>

<form id='update_form' method='post' style="width:33%;height:30%">{% csrf_token %}
    {% for field in update_form %}

            <div style="margin-top: 1.5em">
            {{field.label_tag}}

            {{field}}

            {% for error in field.errors %}
                <small style="color:red;">{{error}}</small>
            {% endfor %}

            {% if update_form.non_field.errors%}
                <div style="color:red">
                    <p>{{update_form.non_field.errors}}</p>
                </div>

            {% endif %}
            </div>
    {% endfor %}
    
    {% for field in pwupdate_form %}

            <div style="margin-top: 1.5em">
            {{field.label_tag}}

            {{field}}
            
            {% for error in field.errors %}
                <small style="color:red;">{{error}}</small><br>
            {% endfor %}

            {% if update_form.non_field.errors%}
                <div style="color:red">
                    <p>{{update_form.non_field.errors}}</p><br>
                </div>

            {% endif %}
            </div>
    {% endfor %}

</form>   

<script>
    submitform = function(){
    document.getElementById("update_form").submit();
    document.getElementById("pwupdate_form").submit();
    }
</script>

<button onclick="submitform()"  style="display: block;margin: 0 auto; margin-top: 1.5em;" >수정</button> 

</div>
{% endblock %}